language: php

sudo: false

php:
  - 7.1
  - 7.2
  - master

matrix:
  allow_failures:
    - php: master
  fast_finish: true

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest --prefer-source --dev"

before_install:
  - composer self-update

install:
  - travis_retry composer update $DEFAULT_COMPOSER_FLAGS

script:
    - vendor/bin/phpunit -c phpunit-simple.xml.dist --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false